#!/usr/bin/env python3
"""
generate_ae_script.py - Generate an After Effects ExtendScript JSX from detections.json.

Reads the detections JSON produced by detect_and_export.py and emits a .jsx file
that, when run inside After Effects, creates Fast Box Blur solid layers for each
track and groups them into a pre-comp named AUTO_REDACTIONS.
"""

import argparse
import json
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# JSX code fragments
# Note: Python string formatting is NOT used for these templates - we use
# explicit str.replace() calls to avoid conflicts with JS curly braces.
# ---------------------------------------------------------------------------

def jsx_header(fps: float, width: int, height: int) -> str:
    return (
        "// AUTO-GENERATED by generate_ae_script.py\n"
        "// Compatible with After Effects 2026 (ExtendScript)\n"
        "// Run via: File > Scripts > Run Script File\n"
        "\n"
        "(function redactVideo() {\n"
        "    var comp = app.project.activeItem;\n"
        "    if (!comp || !(comp instanceof CompItem)) {\n"
        '        alert("Please open a composition and make it active before running this script.");\n'
        "        return;\n"
        "    }\n"
        "\n"
        '    app.beginUndoGroup("Auto Redaction");\n'
        "\n"
        f"    var fps         = {fps};\n"
        f"    var frameWidth  = {width};\n"
        f"    var frameHeight = {height};\n"
        "    var createdLayers = [];\n"
        "\n"
    )


JSX_FOOTER = (
    "\n"
    "    // -----------------------------------------------------------------------\n"
    "    // Group all created blur layers into a pre-comp named AUTO_REDACTIONS\n"
    "    // -----------------------------------------------------------------------\n"
    "    if (createdLayers.length > 0) {\n"
    "        comp.layers.deselectAll();\n"
    "        for (var k = 0; k < createdLayers.length; k++) {\n"
    "            createdLayers[k].selected = true;\n"
    "        }\n"
    "        comp.layers.precompose(\n"
    "            getSelectedLayerIndices(comp),\n"
    '            "AUTO_REDACTIONS",\n'
    "            true\n"
    "        );\n"
    "    }\n"
    "\n"
    "    app.endUndoGroup();\n"
    '    alert("Auto-redaction complete. " + createdLayers.length + " blur layer(s) created.");\n'
    "\n"
    "    // Helper: collect indices of selected layers\n"
    "    function getSelectedLayerIndices(c) {\n"
    "        var indices = [];\n"
    "        for (var i = 1; i <= c.layers.length; i++) {\n"
    "            if (c.layers[i].selected) {\n"
    "                indices.push(i);\n"
    "            }\n"
    "        }\n"
    "        return indices;\n"
    "    }\n"
    "}());\n"
)


# ---------------------------------------------------------------------------
# Per-track JSX generation
# ---------------------------------------------------------------------------

def sanitize_for_jsx_string(s: str) -> str:
    """Escape characters that would break a JSX double-quoted string."""
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\r", "\\r")
    )


def build_single_position(cx: float, cy: float) -> str:
    return (
        f"        solid.property(\"ADBE Transform Group\").property(\"ADBE Position\").setValue([{cx:.4f}, {cy:.4f}]);\n"
    )


def build_keyframe_positions(keyframes: list, fps: float) -> str:
    lines = [
        "        var positionProp = solid.property(\"ADBE Transform Group\").property(\"ADBE Position\");\n"
    ]
    for kf in keyframes:
        t = kf["frame"] / fps
        cx = kf["x"] + kf["w"] / 2
        cy = kf["y"] + kf["h"] / 2
        lines.append(f"        positionProp.setValueAtTime({t:.6f}, [{cx:.4f}, {cy:.4f}]);\n")

    # Apply ease to all keyframes
    lines.append(
        "        // Apply ease to all position keyframes\n"
        "        for (var ki = 1; ki <= positionProp.numKeys; ki++) {\n"
        "            positionProp.setTemporalEaseAtKey(\n"
        "                ki,\n"
        "                [new KeyframeEase(0, 33)],\n"
        "                [new KeyframeEase(0, 33)]\n"
        "            );\n"
        "        }\n"
    )
    return "".join(lines)


def build_track_block(track: dict, fps: float) -> str:
    tid = track["id"]
    matched = track["matched_string"]
    matched_escaped = sanitize_for_jsx_string(matched)
    fs = track["frame_start"]
    fe = track["frame_end"]
    keyframes = track.get("keyframes", [])

    # Bounding box from first keyframe
    if keyframes:
        first_kf = keyframes[0]
        bx, by, bw, bh = first_kf["x"], first_kf["y"], first_kf["w"], first_kf["h"]
    else:
        bx, by, bw, bh = 0, 0, 50, 20

    # Position block
    if len(keyframes) <= 1:
        cx = bx + bw / 2
        cy = by + bh / 2
        position_block = build_single_position(cx, cy)
    else:
        position_block = build_keyframe_positions(keyframes, fps)

    lines = [
        f"    // ---- Track {tid}: \"{matched}\" frames {fs}-{fe} ----\n",
        "    (function() {\n",
        f"        var trackId       = {tid};\n",
        f"        var matchedString = \"{matched_escaped}\";\n",
        f"        var frameStart    = {fs};\n",
        f"        var frameEnd      = {fe};\n",
        "        var inTime        = frameStart / fps;\n",
        "        var outTime       = frameEnd   / fps;\n",
        "\n",
        "        // Bounding box from first keyframe (fallback position)\n",
        f"        var bx = {bx}, by = {by}, bw = {bw}, bh = {bh};\n",
        "\n",
        "        // Create a 100x100 solid - we will scale it to match the bbox\n",
        "        var layerName = \"Blur_\" + trackId + \"_\" + matchedString;\n",
        "        var solidColor = [0, 0, 0];\n",
        "        var solid = comp.layers.addSolid(solidColor, layerName, 100, 100, 1);\n",
        "\n",
        "        // Place it at the top of the layer stack\n",
        "        solid.moveToBeginning();\n",
        "\n",
        "        // Timing\n",
        "        solid.inPoint  = inTime;\n",
        "        solid.outPoint = outTime;\n",
        "\n",
        "        // Blend mode: Normal\n",
        "        solid.blendingMode = BlendingMode.NORMAL;\n",
        "\n",
        "        // Anchor at top-left; position = center of bbox\n",
        "        solid.property(\"ADBE Transform Group\").property(\"ADBE Anchor Point\").setValue([0, 0]);\n",
        "\n",
        "        var centerX = bx + bw / 2;\n",
        "        var centerY = by + bh / 2;\n",
        "\n",
        position_block,
        "\n",
        "        // Scale: solid is 100x100, scale to (bw x bh) pixels\n",
        f"        solid.property(\"ADBE Transform Group\").property(\"ADBE Scale\").setValue([{bw}, {bh}]);\n",
        "\n",
        "        // Apply Fast Box Blur effect\n",
        "        var blur = solid.Effects.addProperty(\"ADBE Box Blur2\");\n",
        "        blur.property(\"Blur Radius\").setValue(25);\n",
        "        blur.property(\"Repeat Edge Pixels\").setValue(true);\n",
        "\n",
        "        createdLayers.push(solid);\n",
        "    }());\n",
        "\n",
    ]
    return "".join(lines)


# ---------------------------------------------------------------------------
# Top-level generator
# ---------------------------------------------------------------------------

def generate_jsx(detections: dict) -> str:
    fps = detections["fps"]
    width = detections["width"]
    height = detections["height"]
    tracks = detections.get("tracks", [])

    parts = [jsx_header(fps, width, height)]
    for track in tracks:
        parts.append(build_track_block(track, fps))
    parts.append(JSX_FOOTER)
    return "".join(parts)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate an After Effects JSX script from detections.json"
    )
    parser.add_argument(
        "--detections",
        default="detections.json",
        help="Path to detections JSON (default: detections.json)",
    )
    parser.add_argument(
        "--output",
        default="redact.jsx",
        help="Output JSX file path (default: redact.jsx)",
    )
    args = parser.parse_args()

    if not Path(args.detections).exists():
        print(f"ERROR: Detections file not found: {args.detections}", file=sys.stderr)
        sys.exit(1)

    with open(args.detections, "r", encoding="utf-8") as fh:
        detections = json.load(fh)

    jsx = generate_jsx(detections)

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(jsx)

    track_count = len(detections.get("tracks", []))
    unique_strings = {t["matched_string"] for t in detections.get("tracks", [])}
    print(f"Generated {args.output}")
    print(f"  Tracks: {track_count}, Unique strings: {len(unique_strings)}")
    if unique_strings:
        for s in sorted(unique_strings):
            print(f"  - {s}")


if __name__ == "__main__":
    main()
