#!/usr/bin/env python3
"""
generate_ae_script.py - Generate an After Effects ExtendScript JSX from detections.json.

Reads the detections JSON produced by detect_and_export.py and emits a .jsx file
that, when run inside After Effects, creates Gaussian Blur solid layers for each
track and groups them into a pre-comp named AUTO_REDACTIONS.

Optimized: all track data is emitted as a single JS array and processed in a
single loop inside ExtendScript, avoiding the overhead of thousands of individual
IIFE calls.  Layer indices are collected during creation so the final precompose
call does not need to iterate all layers.
"""

import argparse
import json
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def sanitize_for_jsx_string(s: str) -> str:
    """Escape characters that would break a JSX double-quoted string."""
    return (
        s.replace("\\", "\\\\")
         .replace('"', '\\"')
         .replace("\n", "\\n")
         .replace("\r", "\\r")
    )


def build_keyframes_js(keyframes: list, fps: float) -> str:
    """Emit a JS array literal of keyframe objects."""
    if not keyframes:
        return "[]"
    parts = []
    for kf in keyframes:
        t = kf["frame"] / fps
        parts.append(
            f"{{t:{t:.6f},bx:{kf['x']},by:{kf['y']},bw:{kf['w']},bh:{kf['h']}}}"
        )
    return "[" + ",".join(parts) + "]"


# ---------------------------------------------------------------------------
# JSX generation
# ---------------------------------------------------------------------------

def generate_jsx(detections: dict) -> str:
    fps: float = detections["fps"]
    width: int = detections["width"]
    height: int = detections["height"]
    tracks: list = detections.get("tracks", [])

    # --- Build the JS tracks array ---
    track_entries = []
    for track in tracks:
        tid = track["id"]
        matched = sanitize_for_jsx_string(track["matched_string"])
        fs = track["frame_start"]
        fe = track["frame_end"]
        keyframes = track.get("keyframes", [])

        if keyframes:
            first_kf = keyframes[0]
            bx, by, bw, bh = first_kf["x"], first_kf["y"], first_kf["w"], first_kf["h"]
        else:
            bx, by, bw, bh = 0, 0, 50, 20

        kf_js = build_keyframes_js(keyframes, fps)

        track_entries.append(
            f"  {{id:{tid},name:\"Blur_{tid}_{matched}\","
            f"inTime:{fs / fps:.6f},outTime:{fe / fps:.6f},"
            f"bx:{bx},by:{by},bw:{bw},bh:{bh},"
            f"keyframes:{kf_js}}}"
        )

    tracks_array = "[\n" + ",\n".join(track_entries) + "\n]"

    jsx = (
        "// AUTO-GENERATED by generate_ae_script.py\n"
        "// Compatible with After Effects 2026 (ExtendScript)\n"
        "// Run via: File > Scripts > Run Script File\n"
        "//\n"
        "// Tip: for large track counts (1000+) enable 'Suppress Dialogs' in\n"
        "//      AE preferences to prevent UI refresh stalls during script execution.\n"
        "\n"
        "(function redactVideo() {\n"
        "    var comp = app.project.activeItem;\n"
        "    if (!comp || !(comp instanceof CompItem)) {\n"
        '        alert("Please open a composition and make it active before running this script.");\n'
        "        return;\n"
        "    }\n"
        "\n"
        '    app.beginUndoGroup("Auto Redaction");\n'
        "\n"
        f"    var fps         = {fps};\n"
        f"    var frameWidth  = {width};\n"
        f"    var frameHeight = {height};\n"
        "\n"
        "    // Verify comp dimensions match the video that was analysed.\n"
        "    // A mismatch means blur positions will be scaled incorrectly.\n"
        "    if (comp.width !== frameWidth || comp.height !== frameHeight) {\n"
        '        if (!confirm("WARNING: Comp size (" + comp.width + "x" + comp.height + ") does not match the analysed video (" + frameWidth + "x" + frameHeight + "). Blur positions may be inaccurate. Continue anyway?")) {\n'
        "            app.endUndoGroup();\n"
        "            return;\n"
        "        }\n"
        "    }\n"
        "\n"
        "    // All track data in one array - processed in a single loop to minimise\n"
        "    // ExtendScript engine overhead compared to individual IIFE calls.\n"
        f"    var tracks = {tracks_array};\n"
        "\n"
        "    // The original footage layer is assumed to be the bottom-most layer.\n"
        "    var footageLayer = comp.layers[comp.layers.length];\n"
        "\n"
        "    // Collect layer indices as we create them so precompose does not need\n"
        "    // to iterate all comp layers at the end.\n"
        "    var layerIndices = [];\n"
        "\n"
        "    for (var i = 0; i < tracks.length; i++) {\n"
        "        var tk = tracks[i];\n"
        "\n"
        "        // Duplicate the footage layer so the blur only affects a copy.\n"
        "        // Using a duplicate + rectangular mask is the correct AE approach:\n"
        "        // a solid with Gaussian Blur only blurs the solid itself (black),\n"
        "        // not the underlying video.\n"
        "        var blurLayer = footageLayer.duplicate();\n"
        "        blurLayer.moveToBeginning();\n"
        "        blurLayer.name = tk.name;\n"
        "        blurLayer.inPoint  = tk.inTime;\n"
        "        blurLayer.outPoint = tk.outTime;\n"
        "\n"
        "        // Add a rectangular mask covering the bounding box.\n"
        "        // The mask vertices are in comp/layer space (top-left origin).\n"
        "        var mask = blurLayer.Masks.addMask();\n"
        "        mask.maskMode = MaskMode.ADD;\n"
        "\n"
        "        if (tk.keyframes.length <= 1) {\n"
        "            // Static mask - set a single shape value\n"
        "            var maskShape = new Shape();\n"
        "            maskShape.vertices = [\n"
        "                [tk.bx,           tk.by],\n"
        "                [tk.bx + tk.bw,   tk.by],\n"
        "                [tk.bx + tk.bw,   tk.by + tk.bh],\n"
        "                [tk.bx,           tk.by + tk.bh]\n"
        "            ];\n"
        "            maskShape.closed = true;\n"
        "            mask.maskPath.setValue(maskShape);\n"
        "        } else {\n"
        "            // Animated mask - set a keyframe for each position sample\n"
        "            for (var ki = 0; ki < tk.keyframes.length; ki++) {\n"
        "                var kf = tk.keyframes[ki];\n"
        "                var kfShape = new Shape();\n"
        "                kfShape.vertices = [\n"
        "                    [kf.bx,           kf.by],\n"
        "                    [kf.bx + kf.bw,   kf.by],\n"
        "                    [kf.bx + kf.bw,   kf.by + kf.bh],\n"
        "                    [kf.bx,           kf.by + kf.bh]\n"
        "                ];\n"
        "                kfShape.closed = true;\n"
        "                mask.maskPath.setValueAtTime(kf.t, kfShape);\n"
        "            }\n"
        "        }\n"
        "\n"
        "        // Apply Gaussian Blur to the duplicated footage layer.\n"
        "        // pixel aspect ratio is assumed to be 1 (square pixels - correct\n"
        "        // for standard screen recordings and most digital video).\n"
        "        var blur = blurLayer.Effects.addProperty(\"ADBE Gaussian Blur 2\");\n"
        "        blur.property(\"Blurriness\").setValue(40);\n"
        "        blur.property(\"Repeat Edge Pixels\").setValue(true);\n"
        "\n"
        "        // Record the layer index directly (no full-layer-list scan needed later)\n"
        "        layerIndices.push(blurLayer.index);\n"
        "    }\n"
        "\n"
        "    // -----------------------------------------------------------------------\n"
        "    // Group all created blur layers into a pre-comp named AUTO_REDACTIONS\n"
        "    // Layer indices were collected during creation - no iteration of all\n"
        "    // layers is required here.\n"
        "    // -----------------------------------------------------------------------\n"
        "    if (layerIndices.length > 0) {\n"
        "        comp.layers.precompose(\n"
        "            layerIndices,\n"
        '            "AUTO_REDACTIONS",\n'
        "            true\n"
        "        );\n"
        "    }\n"
        "\n"
        "    app.endUndoGroup();\n"
        '    alert("Auto-redaction complete. " + layerIndices.length + " blur layer(s) created.");\n'
        "}());\n"
    )

    return jsx


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate an After Effects JSX script from detections.json"
    )
    parser.add_argument(
        "--detections",
        default="detections.json",
        help="Path to detections JSON (default: detections.json)",
    )
    parser.add_argument(
        "--output",
        default="redact.jsx",
        help="Output JSX file path (default: redact.jsx)",
    )
    args = parser.parse_args()

    if not Path(args.detections).exists():
        print(f"ERROR: Detections file not found: {args.detections}", file=sys.stderr)
        sys.exit(1)

    with open(args.detections, "r", encoding="utf-8") as fh:
        detections = json.load(fh)

    jsx = generate_jsx(detections)

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(jsx)

    track_count = len(detections.get("tracks", []))
    unique_strings = {t["matched_string"] for t in detections.get("tracks", [])}
    print(f"Generated {args.output}")
    print(f"  Tracks: {track_count}, Unique strings: {len(unique_strings)}")
    if unique_strings:
        for s in sorted(unique_strings):
            print(f"  - {s}")


if __name__ == "__main__":
    main()
